### Stage 2 scoring components
[[component]]
[component.AnesthPot]
[[component.AnesthPot.endpoint]]
params.checkpoint = '/homes/avasan/REINVENT4/model.pkl'

weight = 0.5  # user chosen name for output
name = "AnesthPot"  # weight to fine-tune the relevance of this component

transform.type = "sigmoid"
transform.high = 15
transform.low = 0
transform.k = 1
